import { app } from "../../scripts/app.js";
import { api } from "../../scripts/api.js";

const NODE_NAME = "PromptWarehouse";
const css = `.pw-backdrop{position:fixed;inset:0;z-index:10000;background:rgba(8,12,18,.72);display:grid;place-items:center;padding:24px;font-family:Inter,system-ui,sans-serif}.pw-modal{width:min(980px,96vw);height:min(720px,92vh);display:grid;grid-template-columns:280px 1fr;background:#151a22;color:#e8edf5;border:1px solid #343d4c;border-radius:14px;box-shadow:0 30px 90px #000a;overflow:hidden}.pw-list{background:#10151c;border-right:1px solid #303846;padding:18px;overflow:auto}.pw-list h2{font-size:17px;margin:0 0 14px}.pw-entry{width:100%;text-align:left;background:transparent;color:#dfe7f2;border:1px solid transparent;border-radius:8px;padding:9px 10px;margin:2px 0;cursor:pointer}.pw-entry:hover,.pw-entry.active{background:#202936;border-color:#394657}.pw-entry small{display:block;color:#8795a8;margin-top:3px}.pw-editor{padding:22px 26px;overflow:auto}.pw-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px}.pw-head strong{font-size:18px}.pw-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.pw-field{display:grid;gap:6px}.pw-field.full{grid-column:1/-1}.pw-field label{font-size:12px;color:#9aa8ba}.pw-field input,.pw-field textarea{box-sizing:border-box;width:100%;border:1px solid #3a4555;border-radius:8px;background:#0f141b;color:#edf3fa;padding:10px 11px;outline:none}.pw-field textarea{min-height:230px;resize:vertical}.pw-field input:focus,.pw-field textarea:focus{border-color:#7aa2d8;box-shadow:0 0 0 3px #527db32b}.pw-actions{display:flex;justify-content:space-between;gap:10px;margin-top:20px}.pw-actions div{display:flex;gap:9px}.pw-btn{border:1px solid #3d495a;border-radius:8px;background:#222b37;color:#eaf0f7;padding:9px 14px;cursor:pointer}.pw-btn:hover{background:#2b3746}.pw-btn.primary{background:#4778ad;border-color:#5c8dc2}.pw-btn.danger{color:#ffb8b2}.pw-empty{color:#8795a8;padding:12px 8px}.pw-status{font-size:12px;color:#93a3b7;margin-top:10px;min-height:18px}@media(max-width:720px){.pw-modal{grid-template-columns:1fr;height:94vh}.pw-list{max-height:210px;border-right:0;border-bottom:1px solid #303846}.pw-grid{grid-template-columns:1fr}}`;
function ensureStyles(){if(document.getElementById("pw-styles"))return;const s=document.createElement("style");s.id="pw-styles";s.textContent=css;document.head.append(s)}
function widget(node,name){return node.widgets?.find((item)=>item.name===name)}
function makeId(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function esc(value=""){return String(value).replace(/[&<>\"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}

async function openWarehouse(node){
 ensureStyles();const response=await api.fetchApi("/prompt-warehouse/prompts");const data=await response.json();let entries=data.entries||[];if(!entries.length)entries=[{id:makeId(),title:"新提示词",group:"基础提示词",prompt:"",width:null,height:null}];let selected=entries[0].id;
 const root=document.createElement("div");root.className="pw-backdrop";root.innerHTML=`<section class="pw-modal" role="dialog" aria-modal="true" aria-label="提示词仓库"><aside class="pw-list"><h2>提示词仓库</h2><div data-list></div></aside><main class="pw-editor"><div class="pw-head"><strong>整理提示词</strong><button class="pw-btn" data-close>关闭</button></div><div class="pw-grid"><div class="pw-field"><label>标题</label><input data-title placeholder="例如：雨夜街景"></div><div class="pw-field"><label>分组</label><input data-group placeholder="例如：基础提示词"></div><div class="pw-field full"><label>提示词</label><textarea data-prompt placeholder="输入完整提示词…"></textarea></div><div class="pw-field"><label>Width（可选）</label><input data-width type="number" min="1" placeholder="未设置"></div><div class="pw-field"><label>Height（可选）</label><input data-height type="number" min="1" placeholder="未设置"></div></div><div class="pw-status" data-status></div><div class="pw-actions"><button class="pw-btn danger" data-delete>删除</button><div><button class="pw-btn" data-new>新增</button><button class="pw-btn" data-use>载入节点</button><button class="pw-btn primary" data-save>保存仓库</button></div></div></main></section>`;document.body.append(root);
 const q=(s)=>root.querySelector(s),fields=["title","group","prompt","width","height"];
 function readForm(){const current=entries.find((e)=>e.id===selected);return{id:current?.id||makeId(),...Object.fromEntries(fields.map((f)=>[f,q(`[data-${f}]`).value.trim()||(f==="width"||f==="height"?null:"")]))}}
 function commit(){if(!selected)return;const index=entries.findIndex((e)=>e.id===selected);if(index>=0)entries[index]=readForm()}
 function render(){q("[data-list]").innerHTML=entries.length?entries.map((e)=>`<button class="pw-entry ${e.id===selected?"active":""}" data-id="${esc(e.id)}">${esc(e.title)}<small>${esc(e.group)}</small></button>`).join(""):`<div class="pw-empty">还没有提示词，点击“新增”。</div>`;const current=entries.find((e)=>e.id===selected);fields.forEach((f)=>q(`[data-${f}]`).value=current?.[f]??"")}
 q("[data-list]").onclick=(event)=>{const button=event.target.closest("[data-id]");if(!button)return;commit();selected=button.dataset.id;render()};
 q("[data-new]").onclick=()=>{commit();const entry={id:makeId(),title:"新提示词",group:"基础提示词",prompt:"",width:null,height:null};entries.push(entry);selected=entry.id;render();q("[data-title]").select()};
 q("[data-delete]").onclick=()=>{if(!selected)return;entries=entries.filter((e)=>e.id!==selected);selected=entries[0]?.id||null;render()};
 q("[data-use]").onclick=()=>{commit();const entry=entries.find((e)=>e.id===selected);if(!entry)return;widget(node,"prompt").value=entry.prompt;widget(node,"width").value=entry.width?String(entry.width):"";widget(node,"height").value=entry.height?String(entry.height):"";widget(node,"random_group").value=entry.group;node.setDirtyCanvas(true,true);q("[data-status]").textContent=`已载入：${entry.title}`};
 q("[data-save]").onclick=async()=>{commit();const status=q("[data-status]");status.textContent="正在保存…";try{const res=await api.fetchApi("/prompt-warehouse/prompts",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({entries})});const body=await res.json();status.textContent=res.ok?"仓库已保存。":(body.error||"保存失败，请检查填写内容。");if(res.ok){entries=body.entries;const groupWidget=widget(node,"random_group");if(groupWidget?.options)groupWidget.options.values=["全部",...new Set(entries.map((e)=>e.group).sort())];render()}}catch(error){status.textContent=`保存失败：${error.message||"无法连接 ComfyUI 后端"}`}};
 const close=()=>root.remove();q("[data-close]").onclick=close;root.onclick=(e)=>{if(e.target===root)close()};root.onkeydown=(e)=>{if(e.key==="Escape")close()};render();
}

app.registerExtension({name:"D33MO.PromptWarehouse",beforeRegisterNodeDef(nodeType,nodeData){if(nodeData.name!==NODE_NAME)return;const created=nodeType.prototype.onNodeCreated;nodeType.prototype.onNodeCreated=function(){const result=created?.apply(this,arguments);const randomIndex=this.widgets?.findIndex((item)=>item.name==="random_group")??-1;if(randomIndex>=0)this.widgets.splice(randomIndex,0,{name:"warehouse_divider",type:"pw-divider",value:null,options:{serialize:false},computeSize(width){return[width,14]},draw(ctx,_node,width,y,height){ctx.save();ctx.strokeStyle="#485364";ctx.globalAlpha=.7;ctx.beginPath();ctx.moveTo(12,y+height/2);ctx.lineTo(width-12,y+height/2);ctx.stroke();ctx.restore()}});this.addWidget("button","打开仓库",null,()=>openWarehouse(this));this.size=[Math.max(this.size[0],360),Math.max(this.size[1],445)];return result};const executed=nodeType.prototype.onExecuted;nodeType.prototype.onExecuted=function(message){executed?.apply(this,arguments);const entry=message?.selected?.[0];if(!entry)return;widget(this,"prompt").value=entry.prompt;widget(this,"width").value=entry.width?String(entry.width):"";widget(this,"height").value=entry.height?String(entry.height):"";this.setDirtyCanvas(true,true)}}});
